### ISSUE TITLE
where to find the "~/Dropbox (Infectious Disease)/ViralLoad_Modelling/related stan/Stan_example_predicting_from_analytically_marginalised_params_WithoutMarginalisation.stan" file?

### ISSUE THREAD

**Issue by liamxg** [ChrisHIV/teaching#1]
Dear. @ChrisHIV,

Could I know where to find the "~/Dropbox (Infectious Disease)/ViralLoad_Modelling/related stan/Stan_example_predicting_from_analytically_marginalised_params_WithoutMarginalisation.stan" file?

Thanks.

Best,
Liam

**Comment by ChrisHIV** [comment]
Some context please - where did you find reference to that file?

**Comment by ChrisHIV** [comment]
Ah a GitHub search succeeded where a local search failed. That file is referenced in [here](https://github.com/ChrisHIV/teaching/blob/main/other_topics/Stan_example_predicting_from_analytically_marginalised_params.Rmd). Note that the file in wrapped in an `{r include = FALSE}` so that it is hidden in the compiled output of the Rmd file (which you can see [here](https://htmlpreview.github.io/?https://github.com/ChrisHIV/teaching/blob/main/other_topics/Stan_example_predicting_from_analytically_marginalised_params.html)). As explained immediately above that line: "Assuming the above code is saved in a file whose path is stored in the R variable `file_stan_code` (e.g. you’ve run `file_stan_code <- "path/to/my_stan.stan"` or similar), we compile it: `model_compiled <- stan_model(file_stan_code)`. i.e. the hidden reference you've come across is just where I've locally stored the stan code displayed within that markdown.

**Comment by liamxg** [comment]
Dear @ChrisHIV,

Could you please upload the file_"stan_code <- "~/Dropbox (Infectious Disease)/ViralLoad_Modelling/related stan/Stan_example_predicting_from_analytically_marginalised_params_WithoutMarginalisation.stan", thnaks.

Best,
Liam

**Comment by ChrisHIV** [comment]
The document you are reading (either the underlying Rmarkdown or its compiled version) clearly explains what the contents of that file should be, and I explained again in my post above. Please read.

**Comment by liamxg** [comment]
Dear @ChrisHIV,

Got it, thanks.

BTW, I have a dataset of more than 5 million raws with 12 columns, could you have help explore it using your method, thanks

Best,
Liam

**Comment by ChrisHIV** [comment]
Nope, sorry. A statistical modelling forum elsewhere might produce a volunteer to help with your work. Good luck

**Comment by liamxg** [comment]
Thanks.
